// src/lib/defaultProviders.ts
// Python tarafındaki providers_config.json ile birebir aynı sağlayıcı/model listesi.
// ÖNEMLİ: Gerçek API anahtarları burada YOK. Sadece hangi env değişkeninden
// okunacağı (api_key_env) tutulur — gerçek değer .env.local dosyasından gelir.

import type { ProvidersFile } from "@/types";

export const DEFAULT_PROVIDERS: ProvidersFile = {
  version: "1.0",
  active_provider: "ollama",
  providers: {
    ollama: {
      label: "Lokal - Ollama",
      description:
        "Tamamen lokal, internet gerekmez. Ollama servisi çalışır olmalı.",
      api_base: "http://localhost:11434",
      api_key_env: null,
      model_prefix: "ollama",
      requires_key: false,
      default_context_window: 8192,
      model_context_windows: {
        "qwen3.8:latest": 8192,
        "qwen3.5:4b": 8192,
        "qwen2.5-coder:7b": 8192,
        "qwen2.5-coder:14b": 8192,
        "qwen3.8:27b": 4096,
        "qwen3:27b": 4096,
        "deepseek-r1:8b": 8192,
        "deepseek-r1:14b": 8192,
        "deepseek-r1:32b": 4096,
      },
      agent_models: {
        coordinator: "ollama/qwen3.8:latest",
        product_manager: "ollama/qwen3.8:latest",
        software_architect: "ollama/qwen3.8:latest",
        developer: "ollama/qwen3.8:latest",
        qa_tester: "ollama/qwen3.8:latest",
        reviewer: "ollama/qwen3.8:latest",
        optimizer: "ollama/qwen3.8:latest",
        documentation_writer: "ollama/qwen3.8:latest",
        devops_engineer: "ollama/qwen3.8:latest",
        custom: "ollama/qwen3.8:latest",
      },
    },
    nvidia: {
      label: "API - NVIDIA NIM (DGX Cloud)",
      description: "NVIDIA NIM üzerinde DeepSeek V4, Nemotron ve açık modeller.",
      api_base: "https://integrate.api.nvidia.com/v1",
      api_key_env: "NVIDIA_API_KEY",
      model_prefix: "openai",
      requires_key: true,
      key_url: "https://build.nvidia.com",
      default_context_window: 65536,
      model_context_windows: {
        "deepseek-ai/deepseek-v4-pro-0813": 65536,
        "deepseek-ai/deepseek-v4-flash-0731": 65536,
        "mistralai/codestral-22b-instruct-v0.1": 32768,
        "nvidia/llama-3.1-nemotron-70b-instruct": 131072,
      },
      agent_models: {
        coordinator: "openai/deepseek-ai/deepseek-v4-pro-0813",
        product_manager: "openai/deepseek-ai/deepseek-v4-pro-0813",
        software_architect: "openai/deepseek-ai/deepseek-v4-pro-0813",
        developer: "openai/deepseek-ai/deepseek-v4-pro-0813",
        qa_tester: "openai/deepseek-ai/deepseek-v4-pro-0813",
        reviewer: "openai/deepseek-ai/deepseek-v4-pro-0813",
        optimizer: "openai/deepseek-ai/deepseek-v4-pro-0813",
        documentation_writer: "openai/deepseek-ai/deepseek-v4-pro-0813",
        devops_engineer: "openai/deepseek-ai/deepseek-v4-pro-0813",
        custom: "openai/deepseek-ai/deepseek-v4-pro-0813",
      },
    },
    openrouter: {
      label: "API - OpenRouter (100+ model)",
      description: "Tek API key ile Llama, Gemini, Claude, GPT ve daha fazlası.",
      api_base: "https://openrouter.ai/api/v1",
      api_key_env: "OPENROUTER_API_KEY",
      model_prefix: "openrouter",
      requires_key: true,
      key_url: "https://openrouter.ai/keys",
      default_context_window: 32768,
      model_context_windows: {
        "qwen/qwen3-235b-a22b": 32768,
        "qwen/qwen2.5-coder-32b-instruct": 32768,
        "anthropic/claude-3.5-sonnet": 200000,
        "openai/gpt-4o": 128000,
        "google/gemini-2.0-flash": 1000000,
        "deepseek/deepseek-r1": 65536,
      },
      agent_models: {
        coordinator: "openrouter/qwen/qwen3-235b-a22b",
        product_manager: "openrouter/qwen/qwen3-235b-a22b",
        software_architect: "openrouter/qwen/qwen3-235b-a22b",
        developer: "openrouter/qwen/qwen2.5-coder-32b-instruct",
        qa_tester: "openrouter/qwen/qwen2.5-coder-32b-instruct",
        reviewer: "openrouter/qwen/qwen3-235b-a22b",
        optimizer: "openrouter/qwen/qwen3-235b-a22b",
        documentation_writer: "openrouter/qwen/qwen3-235b-a22b",
        devops_engineer: "openrouter/qwen/qwen3-235b-a22b",
        custom: "openrouter/qwen/qwen3-235b-a22b",
      },
    },
    moonshot: {
      label: "API - Kimi K2 (Moonshot AI)",
      description: "Çok güçlü, ajan görevlerinde uzman. Ücretsiz tier mevcut.",
      api_base: "https://api.moonshot.cn/v1",
      api_key_env: "MOONSHOT_API_KEY",
      model_prefix: "moonshot",
      requires_key: true,
      key_url: "https://platform.moonshot.cn",
      default_context_window: 131072,
      model_context_windows: {
        "kimi-k2": 131072,
        "moonshot-v1-8k": 8192,
        "moonshot-v1-32k": 32768,
        "moonshot-v1-128k": 131072,
      },
      agent_models: {
        coordinator: "moonshot/kimi-k2",
        product_manager: "moonshot/kimi-k2",
        software_architect: "moonshot/kimi-k2",
        developer: "moonshot/kimi-k2",
        qa_tester: "moonshot/kimi-k2",
        reviewer: "moonshot/kimi-k2",
        optimizer: "moonshot/kimi-k2",
        documentation_writer: "moonshot/moonshot-v1-8k",
        devops_engineer: "moonshot/kimi-k2",
        custom: "moonshot/kimi-k2",
      },
    },
    lm_studio: {
      label: "Lokal - LM Studio",
      description: "LM Studio GUI uygulaması üzerinden lokal model.",
      api_base: "http://localhost:1234/v1",
      api_key_env: null,
      model_prefix: "lm_studio",
      requires_key: false,
      default_context_window: 8192,
      model_context_windows: {
        "lm_studio/qwen3.5-9b": 8192,
        "lm_studio/qwen2.5-coder-7b": 8192,
      },
      agent_models: {
        coordinator: "lm_studio/qwen3.5-9b",
        product_manager: "lm_studio/qwen3.5-9b",
        software_architect: "lm_studio/qwen3.5-9b",
        developer: "lm_studio/qwen2.5-coder-7b",
        qa_tester: "lm_studio/qwen2.5-coder-7b",
        reviewer: "lm_studio/qwen3.5-9b",
        optimizer: "lm_studio/qwen3.5-9b",
        documentation_writer: "lm_studio/qwen3.5-9b",
        devops_engineer: "lm_studio/qwen3.5-9b",
        custom: "lm_studio/qwen3.5-9b",
      },
    },
    llama_cpp: {
      label: "Lokal - llama.cpp (llama-server)",
      description: "Saf C++ motoru, minimum RAM ve maksimum verimlilik. Port 8080, 32k context.",
      api_base: "http://localhost:8080/v1",
      api_key_env: null,
      model_prefix: "openai",
      requires_key: false,
      // llama_server_baslat.sh -c 32768 ile başlatılıyor
      default_context_window: 32768,
      model_context_windows: { default: 32768 },
      agent_models: {
        // llama.cpp tek-model server: model adı boş bırakılır, sunucu mevcut modeli kullanır
        coordinator: "openai/",
        product_manager: "openai/",
        software_architect: "openai/",
        developer: "openai/",
        qa_tester: "openai/",
        reviewer: "openai/",
        optimizer: "openai/",
        documentation_writer: "openai/",
        devops_engineer: "openai/",
        custom: "openai/",
      },
    },
  },
};

export const DEFAULT_SETTINGS_JSON = {
  default_model: "ollama/qwen3.8:latest",
  coordinator_name: "MYF-Agent",
  think_mode: true,
  warmup: false,
  theme: "cyan",
  temperature: 0.2,
  max_tokens: 8192,
  planning_model: "ollama/qwen3.8:latest",
  code_model: "ollama/qwen3.8:latest",
  micro_fix_model: "ollama/qwen3.8:latest",
  coordinator_model: "ollama/qwen3.8:latest",
  micro_fix_max_tries: 3,
  full_autonomy_cap: 100,
  repomap_tokens: 2048,
  permission_mode: "session_allow" as const,
  auto_audit_log: true,
  execution_mode: "interactive" as const,
  active_provider: "ollama",
};
